# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 11:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appmapachile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='creaci\xf3n')),
                ('modificacion', models.DateTimeField(auto_now_add=True, verbose_name='modificaci\xf3n')),
                ('rut', models.CharField(max_length=15, unique=True, verbose_name='RUT')),
                ('nombres', models.CharField(max_length=24, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=24, verbose_name='apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('foto', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='client/%Y/%m/%d/', verbose_name='foto')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('telefono_personal', models.CharField(blank=True, max_length=16, null=True, verbose_name='telefono personal')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=16, null=True, verbose_name='telefono emergencia')),
                ('direccion', models.CharField(blank=True, max_length=32, null=True)),
                ('autor', models.ForeignKey(auto_created=True, blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_autor', to=settings.AUTH_USER_MODEL)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmapachile.Comuna')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='HistoricalClient',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_created=True, blank=True, editable=False, verbose_name='creaci\xf3n')),
                ('modificacion', models.DateTimeField(blank=True, editable=False, verbose_name='modificaci\xf3n')),
                ('rut', models.CharField(db_index=True, max_length=15, verbose_name='RUT')),
                ('nombres', models.CharField(max_length=24, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=24, verbose_name='apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('foto', models.TextField(blank=True, max_length=100, null=True, verbose_name='foto')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('telefono_personal', models.CharField(blank=True, max_length=16, null=True, verbose_name='telefono personal')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=16, null=True, verbose_name='telefono emergencia')),
                ('direccion', models.CharField(blank=True, max_length=32, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('autor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('comuna', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appmapachile.Comuna')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Client',
            },
        ),
    ]
