# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdirectorio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Cliente',
        ),
        migrations.RenameModel(
            old_name='HistoricalClient',
            new_name='HistoricalCliente',
        ),
    ]
