# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appdirectorio', '0003_auto_20171102_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(help_text='Ej: P\xe9rez Pereira', max_length=24, verbose_name='apellidos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='autor',
            field=models.ForeignKey(auto_created=True, blank=True, help_text='Nombre del autor, aparecer\xe1 solo para ver quien agreg\xf3 al cliente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='comuna',
            field=models.ForeignKey(help_text='Seleccionar una comuna asociada al cliente', on_delete=django.db.models.deletion.CASCADE, to='appmapachile.Comuna'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='creacion',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, help_text='Fecha en la que se cre\xf3 el registro del cliente', verbose_name='creaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, help_text='Direcci\xf3n asociada al cliente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, help_text='nombre@dominio.cl', max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='01/02/1991', null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='cliente/%Y/%m/%d', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='modificacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se realiza algun cambio en el cliente guardado', verbose_name='modificaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(help_text='Ej: Pedro Patricio', max_length=24, verbose_name='nombres'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(blank=True, help_text='Ej: 12345678-9', max_length=15, null=True, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_emergencia',
            field=models.CharField(blank=True, help_text='Ej: +56987654321', max_length=16, null=True, verbose_name='telefono emergencia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_personal',
            field=models.CharField(blank=True, help_text='Ej: +56987654321', max_length=16, null=True, verbose_name='telefono personal'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='apellidos',
            field=models.CharField(help_text='Ej: P\xe9rez Pereira', max_length=24, verbose_name='apellidos'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='creacion',
            field=models.DateTimeField(auto_created=True, blank=True, editable=False, help_text='Fecha en la que se cre\xf3 el registro del cliente', verbose_name='creaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='direccion',
            field=models.CharField(blank=True, help_text='Direcci\xf3n asociada al cliente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='email',
            field=models.EmailField(blank=True, help_text='nombre@dominio.cl', max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='01/02/1991', null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='modificacion',
            field=models.DateTimeField(blank=True, editable=False, help_text='Fecha en la que se realiza algun cambio en el cliente guardado', verbose_name='modificaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='nombres',
            field=models.CharField(help_text='Ej: Pedro Patricio', max_length=24, verbose_name='nombres'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='rut',
            field=models.CharField(blank=True, db_index=True, help_text='Ej: 12345678-9', max_length=15, null=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='telefono_emergencia',
            field=models.CharField(blank=True, help_text='Ej: +56987654321', max_length=16, null=True, verbose_name='telefono emergencia'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='telefono_personal',
            field=models.CharField(blank=True, help_text='Ej: +56987654321', max_length=16, null=True, verbose_name='telefono personal'),
        ),
    ]
