# coding=utf-8
"""
Django settings for tipster project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/

django-admin.py makemessages -l en
and
python manage.py compilemessages

geoposition map in Django==1.11
pip install https://github.com/philippbosch/django-geoposition/archive/django-1.11.zip

$ pip freeze > requirements.txt
$ pip install -r requirements.txt
"""
#https://docs.webfaction.com/software/static.html?highlight=http%2520to%2520https#redirecting-from-http-to-https
#for http to https

import os

from django.utils.translation import ugettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_DIR = os.path.dirname(__file__)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3mf_oml#o_n9+dv1!va4ayo$na@slai%@%_yx@aty+g8%g1v!j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [u'127.0.0.1', u'tipster.cl', u'www.tipster.cl', u'192.168.1.8', u'192.168.1.10', u'192.168.1.7', u'0.0.0.0']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'simple_history',
    'easy_thumbnails',
    "geoposition",
    'social_core',
    'social_django',

    # apps:
    'appavisos.apps.AppavisosConfig',
    'appcontacto.apps.AppcontactoConfig',
    'appdirectorio.apps.AppdirectorioConfig',
    'appmapachile.apps.AppmapachileConfig',

]

STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.CachedStaticFilesStorage'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',  # <--
]

ROOT_URLCONF = 'tipster.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.media',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',  # <--
                'social_django.context_processors.login_redirect', # <--
            ],
        },
    },
]

WSGI_APPLICATION = 'tipster.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'es-cl'
ugettext = lambda s: s
LANGUAGES = [
    ('es', _('Spanish')),
    ('en', _('English')),
    #('de', _('German')),
]
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_L10N = True
USE_TZ = True

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_ROOT = ('/home/gabrielcea/webapps/tipster_static')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join('media')

# for geoposition
GEOPOSITION_GOOGLE_MAPS_API_KEY = 'AIzaSyBoBxQH6J5sUMk2TEhmqE2IXQ0yeCvromI'
GEOPOSITION_MAP_OPTIONS = {'minZoom': 3, 'maxZoom': 17}
GEOPOSITION_MARKER_OPTIONS = {
    'cursor': 'move'
}

# for easy thumbnail
THUMBNAIL_ALIASES = {
    '': {
        'easy_thumbnails': {'size': (250, 250), 'crop': True},
        'portada-ciudad': {'size': (255, 65), 'crop': True},
        'profile-background': {'size': (251, 177), 'crop': True},
        'background-store': {'size': (1440, 800), 'crop': True, 'quality': 70},
        'background': {'size': (1440, 800), 'crop': True },
        'min_tienda': {'size': (360, 250), 'crop': True},
        'min_evento': {'size': (600, 300), 'crop': True},
        'min_directorio': {'size': (130, 130), 'crop': True},
    },
}

# for email
ADMINS = (('Paul', 'hallo.paul@icloud.com'))
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST = 'smtp.webfaction.com'
EMAIL_HOST_USER = 'tipster_noresponder'
EMAIL_HOST_PASSWORD = 'tipster12345'
# EMAIL_SSL_KEYFILE = None
DEFAULT_FROM_EMAIL = 'noresponder@tipster.cl'
# SERVER_EMAIL = 'HOLA@EMAIL.CL'
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

SOCIAL_AUTH_FACEBOOK_API_VERSION = '2.12'
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
#LOGIN_REDIRECT_URL = 'home'
#SOCIAL_AUTH_LOGIN_ERROR_URL = 'error_facebook'

SOCIAL_AUTH_FACEBOOK_KEY = '130283367813335'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = 'd73fccf4a2f388fa47e1a88ef32c6007'  # App Secret

#SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']


'''
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'locate': 'en_US',
    'fields': 'name, email,'
}
'''

SOCIAL_AUTH_FACEBOOK_IGNORE_DEFAULT_SCOPE = True
SOCIAL_AUTH_FACEBOOK_SCOPE = [
    'email'
]

#SOCIAL_AUTH_RAISE_EXCEPTIONS = False
#SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

GRAPHENE = {
    'SCHEMA': 'schemas.schema',
}
#SOCIAL_AUTH_FACEBOOK_REDIRECT_STATE_FIELD = 'state'
#SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email',  # <--- este
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

# Se utiliza el script de facebook en js para capturar la uid de usuario
# asi no se procesa un inicio de sesion desde el sitio
# es lo unico que se encontró como solución, debido a los cambios en las politicas actuales de FB
