# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcontacto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacto',
        ),
        migrations.RenameModel(
            old_name='HistoricalContact',
            new_name='HistoricalContacto',
        ),
    ]
