# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcategoria',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
