# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0003_auto_20171102_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='frase',
        ),
        migrations.AddField(
            model_name='horario',
            name='dias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='horas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='\xbfSe encuentra activo?'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 2, 15, 25, 57, 93689, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 2, 15, 25, 57, 93730, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='foto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 11, 2, 15, 25, 57, 99828, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='foto',
            name='fecha_modificacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 15, 25, 57, 99868, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcategoria',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='\xbfSe encuentra activo?'),
        ),
        migrations.AlterField(
            model_name='historicalevento',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 2, 15, 25, 57, 93689, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='historicalevento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 2, 15, 25, 57, 93730, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='historicaltienda',
            name='expiracion',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 2, 15, 25, 57, 87437, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tienda_horario', to='appavisos.Tienda'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='expiracion',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 2, 15, 25, 57, 87437, tzinfo=utc), null=True),
        ),
    ]
