# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0004_auto_20171102_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, default='django.utils.timezone.now', null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default='django.utils.timezone.now', null=True),
        ),
        migrations.AlterField(
            model_name='foto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_created=True, default='django.utils.timezone.now'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='fecha_modificacion',
            field=models.DateTimeField(default='django.utils.timezone.now'),
        ),
        migrations.AlterField(
            model_name='historicalevento',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, default='django.utils.timezone.now', null=True),
        ),
        migrations.AlterField(
            model_name='historicalevento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default='django.utils.timezone.now', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltienda',
            name='expiracion',
            field=models.DateField(blank=True, default='django.utils.timezone.now', null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='expiracion',
            field=models.DateField(blank=True, default='django.utils.timezone.now', null=True),
        ),
    ]
