# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0006_auto_20171102_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltienda',
            name='horario_fin_semana_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Cierre durante fin de semana'),
        ),
        migrations.AddField(
            model_name='historicaltienda',
            name='horario_fin_semana_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Apertura durante fin de semana'),
        ),
        migrations.AddField(
            model_name='historicaltienda',
            name='horario_semana_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Cierre durante la semana'),
        ),
        migrations.AddField(
            model_name='historicaltienda',
            name='horario_semana_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Apertura durante la semana'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='horario_fin_semana_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Cierre durante fin de semana'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='horario_fin_semana_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Apertura durante fin de semana'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='horario_semana_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Cierre durante la semana'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='horario_semana_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Apertura durante la semana'),
        ),
    ]
