# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0007_auto_20171102_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltienda',
            name='tipster_recomienda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='tipster_recomienda',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='menu',
            field=models.BooleanField(default=False, verbose_name='en buscador'),
        ),
        migrations.AlterField(
            model_name='historicalcategoria',
            name='menu',
            field=models.BooleanField(default=False, verbose_name='en buscador'),
        ),
    ]
