# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0008_auto_20171102_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltienda',
            name='panorama_para',
            field=models.CharField(blank=True, help_text='Aparecer\xe1 arriba de "abierto ahora"', max_length=64, null=True, verbose_name='Panorama para:'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='panorama_para',
            field=models.CharField(blank=True, help_text='Aparecer\xe1 arriba de "abierto ahora"', max_length=64, null=True, verbose_name='Panorama para:'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='cabecera',
            field=models.BooleanField(default=False, help_text='aparecer\xe1 en la cabecera, si se agrega m\xe1s de una con esta opci\xf2n se generar\xe0 un slider; s\xf3lo v\xe1lido para tiendas'),
        ),
        migrations.AlterField(
            model_name='historicalmarca',
            name='activo',
            field=models.BooleanField(default=True, help_text='Se encuentra activa o no la marca; Una marca puede estar desactivada y guardada'),
        ),
        migrations.AlterField(
            model_name='historicalmarca',
            name='busquedas',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalmarca',
            name='en_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalmarca',
            name='logo',
            field=models.TextField(blank=True, help_text='Ojal\xe1 png o de acorde al fondo', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='activo',
            field=models.BooleanField(default=True, help_text='Se encuentra activa o no la marca; Una marca puede estar desactivada y guardada'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='busquedas',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='en_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Ojal\xe1 png o de acorde al fondo', null=True, upload_to='tienda'),
        ),
    ]
