# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0009_auto_20171127_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltienda',
            name='panorama_destacado',
            field=models.BooleanField(default=False, verbose_name='Panoramas'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='panorama_destacado',
            field=models.BooleanField(default=False, verbose_name='Panoramas'),
        ),
        migrations.AlterField(
            model_name='historicaltienda',
            name='panorama_para',
            field=models.CharField(blank=True, help_text='Aparecer\xe1 arriba de "abierto ahora"', max_length=64, null=True, verbose_name='Panorama para'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='panorama_para',
            field=models.CharField(blank=True, help_text='Aparecer\xe1 arriba de "abierto ahora"', max_length=64, null=True, verbose_name='Panorama para'),
        ),
    ]
