# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0010_auto_20171127_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='redireccion',
            field=models.BooleanField(default=False, help_text='Al pedir m\xe1s informaci\xf3nredireccionar\xe1', verbose_name='Redireccionar'),
        ),
        migrations.AddField(
            model_name='historicalevento',
            name='redireccion',
            field=models.BooleanField(default=False, help_text='Al pedir m\xe1s informaci\xf3nredireccionar\xe1', verbose_name='Redireccionar'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='activo',
            field=models.BooleanField(default=False, help_text='Si se encuentra activo ser\xe1 visible', verbose_name='Activado'),
        ),
        migrations.AlterField(
            model_name='historicalevento',
            name='activo',
            field=models.BooleanField(default=False, help_text='Si se encuentra activo ser\xe1 visible', verbose_name='Activado'),
        ),
    ]
