# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0011_auto_20171127_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcomentario',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
