# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 07:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0012_auto_20171128_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltienda',
            name='habilitacion_comentarios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tienda',
            name='habilitacion_comentarios',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='evaluacion',
            field=models.PositiveSmallIntegerField(default=3, help_text='del 1 al 5', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='historicalcomentario',
            name='evaluacion',
            field=models.PositiveSmallIntegerField(default=3, help_text='del 1 al 5', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
