# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0013_auto_20171128_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltienda',
            name='logo',
            field=models.TextField(blank=True, help_text='Ser\xe1 procesada como archivo, no se redimensionar\xe1 ni recortar\xe1, solo se modificar\xe1 su tama\xf1o de ancho y largo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='logo',
            field=models.FileField(blank=True, help_text='Ser\xe1 procesada como archivo, no se redimensionar\xe1 ni recortar\xe1, solo se modificar\xe1 su tama\xf1o de ancho y largo', null=True, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(verbose_name='comentario'),
        ),
        migrations.AlterField(
            model_name='historicalcomentario',
            name='texto',
            field=models.TextField(verbose_name='comentario'),
        ),
    ]
