# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0013_auto_20171128_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(verbose_name='comentario'),
        ),
        migrations.AlterField(
            model_name='historicalcomentario',
            name='texto',
            field=models.TextField(verbose_name='comentario'),
        ),
    ]
