# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0014_auto_20171202_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estilos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_fondo_principal', models.CharField(default='000000', max_length=30)),
                ('color_fondo_mapa', models.CharField(default='000000', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_import_url', models.CharField(help_text='solo el link', max_length=999)),
                ('font_family', models.CharField(help_text='el contenido de "font-family"', max_length=999)),
            ],
            options={
                'verbose_name': 'Tipograf\xeda',
                'verbose_name_plural': 'Tipograf\xedas',
            },
        ),
        migrations.AddField(
            model_name='estilos',
            name='tipografia_textos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipografia_textos_tipografia', to='appavisos.Tipografia'),
        ),
        migrations.AddField(
            model_name='estilos',
            name='tipografia_titulos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipografia_titulos_tipografia', to='appavisos.Tipografia'),
        ),
        migrations.AddField(
            model_name='historicaltienda',
            name='estilos',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appavisos.Estilos'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='estilos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appavisos.Estilos'),
        ),
    ]
