# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0015_auto_20171204_0417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estilos',
            new_name='Estilo',
        ),
        migrations.AlterModelOptions(
            name='estilo',
            options={'verbose_name': 'Estilo', 'verbose_name_plural': 'Estilos'},
        ),
    ]
