# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0016_auto_20171204_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='estilo',
            name='color_letra_destacada',
            field=models.CharField(blank=True, default='7b1fa2', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='estilo',
            name='color_letra_subtitulo',
            field=models.CharField(blank=True, default='7b1fa2', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='estilo',
            name='color_letra_titulo',
            field=models.CharField(blank=True, default='8e24aa', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='estilo',
            name='color_fondo_mapa',
            field=models.CharField(blank=True, default='7b1fa2', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='estilo',
            name='color_fondo_principal',
            field=models.CharField(blank=True, default='8e24aa', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tipografia',
            name='font_family',
            field=models.CharField(help_text='ej: \'Spectral SC\', serif"', max_length=999),
        ),
        migrations.AlterField(
            model_name='tipografia',
            name='style_import_url',
            field=models.CharField(help_text='ej: https://fonts.googleapis.com/css?family=Spectral+SC ', max_length=999),
        ),
    ]
