# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0017_auto_20171204_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='estilo',
            name='nombre',
            field=models.CharField(blank=True, default='Nombre del estilo', max_length=100, null=True),
        ),
    ]
