# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0018_estilo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='estilo',
            name='color_fondo_resennas',
            field=models.CharField(blank=True, default='7b1fa2', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='estilo',
            name='color_letra_resennas',
            field=models.CharField(blank=True, default='7b1fa2', max_length=30, null=True),
        ),
    ]
