# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0020_auto_20171204_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estilo',
            old_name='color_letra_subtitulo',
            new_name='color_letra_textos',
        ),
        migrations.RemoveField(
            model_name='estilo',
            name='color_letra_titulo',
        ),
    ]
