# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0021_auto_20171204_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='estilo',
            name='color_letra_titulos',
            field=models.CharField(blank=True, default='000000', max_length=30, null=True),
        ),
    ]
