# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0022_estilo_color_letra_titulos'),
        ('appavisos', '0014_auto_20171201_0425'),
    ]

    operations = [
    ]
