# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0023_merge_20171204_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='id_usuario',
            field=models.CharField(default=django.utils.timezone.now, max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcomentario',
            name='id_usuario',
            field=models.CharField(default='55', max_length=999),
            preserve_default=False,
        ),
    ]
