# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0024_auto_20171222_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='id_usuario',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tienda_comentario', to='appavisos.Tienda'),
        ),
        migrations.AlterField(
            model_name='historicalcomentario',
            name='id_usuario',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomentario',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomentario',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='comentario'),
        ),
    ]
