# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0024_auto_20171222_1538'),
        ('appavisos', '0025_auto_20171222_1659'),
    ]

    operations = [
    ]
