# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-13 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0026_merge_20171222_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='id_usuario',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='comentario'),
        ),
        migrations.AlterField(
            model_name='historicalcomentario',
            name='id_usuario',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomentario',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='comentario'),
        ),
    ]
