# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0028_auto_20180319_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='tipo_panorama',
        ),
        migrations.RemoveField(
            model_name='historicalevento',
            name='tipo_panorama',
        ),
        migrations.AddField(
            model_name='historicaltienda',
            name='tipo_panorama',
            field=models.CharField(blank=True, choices=[('A', 'Desayuno & Almuerzo'), ('B', 'Panorama Tarde'), ('C', 'Panorama Noche')], max_length=2, null=True, verbose_name='tipo de evento'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='tipo_panorama',
            field=models.CharField(blank=True, choices=[('A', 'Desayuno & Almuerzo'), ('B', 'Panorama Tarde'), ('C', 'Panorama Noche')], max_length=2, null=True, verbose_name='tipo de evento'),
        ),
    ]
