# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0029_auto_20180319_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltienda',
            name='horario_fin_semana_fin',
        ),
        migrations.RemoveField(
            model_name='historicaltienda',
            name='horario_fin_semana_inicio',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='horario_fin_semana_fin',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='horario_fin_semana_inicio',
        ),
        migrations.AddField(
            model_name='historicaltienda',
            name='precio',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='precio',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
