# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0031_auto_20180325_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estilo',
            name='color_fondo_mapa',
        ),
        migrations.RemoveField(
            model_name='estilo',
            name='color_fondo_principal',
        ),
        migrations.RemoveField(
            model_name='estilo',
            name='color_fondo_resennas',
        ),
        migrations.RemoveField(
            model_name='estilo',
            name='color_letra_destacada',
        ),
        migrations.RemoveField(
            model_name='estilo',
            name='color_letra_nombre_subtitulo',
        ),
        migrations.RemoveField(
            model_name='estilo',
            name='color_letra_nombre_titulo',
        ),
        migrations.RemoveField(
            model_name='estilo',
            name='color_letra_resennas',
        ),
        migrations.RemoveField(
            model_name='estilo',
            name='color_letra_textos',
        ),
        migrations.RemoveField(
            model_name='estilo',
            name='color_letra_titulos',
        ),
        migrations.RemoveField(
            model_name='estilo',
            name='tipografia_textos',
        ),
        migrations.RemoveField(
            model_name='estilo',
            name='tipografia_titulos',
        ),
        migrations.AddField(
            model_name='estilo',
            name='galeria_background',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estilo',
            name='galeria_titulo_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estilo',
            name='horarios_background',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estilo',
            name='horarios_horario_dias_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estilo',
            name='horarios_horario_relojhoras_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estilo',
            name='horarios_titulo_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estilo',
            name='mapa_background',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estilo',
            name='mapa_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estilo',
            name='mapa_info_back',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estilo',
            name='mapa_info_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estilo',
            name='resennas_fecha_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estilo',
            name='resennas_tituloycontenidonombre_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estilo',
            name='sociales_info_background',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estilo',
            name='sociales_titulo_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estilo',
            name='somos_background',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estilo',
            name='somos_titulo_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estilo',
            name='somos_titulo_descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estilo',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
