# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0031_auto_20180325_2152'),
        ('appavisos', '0031_auto_20180322_0617'),
    ]

    operations = [
    ]
