# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0032_merge_20180326_0013'),
        ('appavisos', '0032_auto_20180330_0429'),
    ]

    operations = [
    ]
