# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0033_merge_20180330_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='estilo',
            name='resennas_tituloycontenidonombre_background',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
