# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-31 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0033_estilo_resennas_tituloycontenidonombre_background'),
        ('appavisos', '0034_estilo_resennas_tituloycontenidonombre_background'),
    ]

    operations = [
    ]
