# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 23:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0034_auto_20180402_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltienda',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='evaluacion',
            field=models.PositiveSmallIntegerField(default=4, help_text='del 1 al 7', validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='historicalcomentario',
            name='evaluacion',
            field=models.PositiveSmallIntegerField(default=4, help_text='del 1 al 7', validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='historicaltienda',
            name='expiracion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='expiracion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
