# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 23:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0035_auto_20180404_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltienda',
            name='expiracion',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 4, 20, 35, 57, 549852), null=True),
        ),
        migrations.AlterField(
            model_name='historicaltienda',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 4, 20, 35, 57, 549891), null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='expiracion',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 4, 20, 35, 57, 549852), null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 4, 20, 35, 57, 549891), null=True),
        ),
    ]
