# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0035_merge_20180331_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='historicalcomentario',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='historicaltienda',
            name='frase',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='historicaltienda',
            name='panorama_para',
            field=models.CharField(blank=True, help_text='Aparecer\xe1 arriba de "abierto ahora"', max_length=64, null=True, verbose_name='Recomendado para'),
        ),
        migrations.AlterField(
            model_name='historicaltienda',
            name='precio',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Precio desde'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='frase',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='panorama_para',
            field=models.CharField(blank=True, help_text='Aparecer\xe1 arriba de "abierto ahora"', max_length=64, null=True, verbose_name='Recomendado para'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='precio',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Precio desde'),
        ),
    ]
