# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0034_auto_20180402_1830'),
        ('appavisos', '0036_auto_20180403_0551'),
    ]

    operations = [
    ]
