# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 21:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0036_auto_20180404_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltienda',
            name='expiracion',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 8, 18, 4, 5, 875311), null=True),
        ),
        migrations.AlterField(
            model_name='historicaltienda',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 8, 18, 4, 5, 875348), null=True),
        ),
        migrations.AlterField(
            model_name='historicaltienda',
            name='tipo_panorama',
            field=models.CharField(blank=True, choices=[('A', 'Panorama Ma\xf1ana'), ('B', 'Panorama Tarde'), ('C', 'Panorama Noche')], max_length=2, null=True, verbose_name='tipo de evento'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='expiracion',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 8, 18, 4, 5, 875311), null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 8, 18, 4, 5, 875348), null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='tipo_panorama',
            field=models.CharField(blank=True, choices=[('A', 'Panorama Ma\xf1ana'), ('B', 'Panorama Tarde'), ('C', 'Panorama Noche')], max_length=2, null=True, verbose_name='tipo de evento'),
        ),
    ]
