# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0037_merge_20180403_0739'),
        ('appavisos', '0036_auto_20180404_2035'),
    ]

    operations = [
    ]
