# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 02:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0038_merge_20180404_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltienda',
            name='expiracion',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 12, 23, 17, 35, 631964), null=True),
        ),
        migrations.AlterField(
            model_name='historicaltienda',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 12, 23, 17, 35, 631995), null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='expiracion',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 12, 23, 17, 35, 631964), null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 12, 23, 17, 35, 631995), null=True),
        ),
    ]
