# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appavisos', '0039_auto_20180412_2317'),
        ('appavisos', '0039_auto_20180413_0313'),
    ]

    operations = [
    ]
