# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Valdivia, Osorno...', max_length=50, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Comuna de Chile',
                'verbose_name_plural': 'Comunas de Chile',
            },
        ),
        migrations.CreateModel(
            name='HistoricalComuna',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, help_text='Valdivia, Osorno...', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Comuna de Chile',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProvincia',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, help_text='Valdivia, Osorno...', max_length=50)),
                ('region', models.CharField(choices=[('XV', 'Arica y Parinacota'), ('II', 'Tarapac\xe1'), ('II', 'Antofagasta'), ('III', 'Atacama'), ('IV', 'Coquimbo'), ('V', 'Valpara\xedso'), ('RM', 'Metropolitana de Santiago'), ('VI', "O'Higgins"), ('VII', 'Maule'), ('VIII', 'B\xedo-B\xedo'), ('IX', 'La Araucan\xeda'), ('XIV', 'Los R\xedos'), ('X', 'Los Lagos'), ('XI', 'Ays\xe9n'), ('XII', 'Magallanes')], max_length=4)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Provincia',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Valdivia, Osorno...', max_length=50, unique=True)),
                ('region', models.CharField(choices=[('XV', 'Arica y Parinacota'), ('II', 'Tarapac\xe1'), ('II', 'Antofagasta'), ('III', 'Atacama'), ('IV', 'Coquimbo'), ('V', 'Valpara\xedso'), ('RM', 'Metropolitana de Santiago'), ('VI', "O'Higgins"), ('VII', 'Maule'), ('VIII', 'B\xedo-B\xedo'), ('IX', 'La Araucan\xeda'), ('XIV', 'Los R\xedos'), ('X', 'Los Lagos'), ('XI', 'Ays\xe9n'), ('XII', 'Magallanes')], max_length=4)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.AddField(
            model_name='historicalcomuna',
            name='provincia',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appmapachile.Provincia'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna_ciudad', to='appmapachile.Provincia'),
        ),
    ]
