# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appmapachile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='portada',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Imagen asociada a Ciudad - Comuna', null=True, upload_to='pic_ciudad'),
        ),
        migrations.AddField(
            model_name='historicalcomuna',
            name='portada',
            field=models.TextField(blank=True, help_text='Imagen asociada a Ciudad - Comuna', max_length=100, null=True),
        ),
    ]
