# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmapachile', '0002_auto_20180325_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='activacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcomuna',
            name='activacion',
            field=models.BooleanField(default=False),
        ),
    ]
